name: Test Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test server connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "=== Connected to server successfully! ==="
            echo "Current directory: $(pwd)"
            echo "Current user: $(whoami)"
            
            echo "=== Checking project directory ==="
            if [ -d "/var/www/miro" ]; then
              echo "✅ Project directory exists"
              cd /var/www/miro
              echo "Project path: $(pwd)"
              ls -la
            else
              echo "❌ Project directory does not exist"
              echo "Creating project directory..."
              sudo mkdir -p /var/www/miro
              sudo chown sequent:sequent /var/www/miro
            fi
            
            echo "=== Server info ==="
            uname -a
            df -h
