name: Test Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test server connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "=== Connected to server successfully! ==="
            echo "Current directory: $(pwd)"
            echo "Current user: $(whoami)"
            echo "Server info: $(uname -a)"
            echo "Available disk space:"
            df -h
            echo "=== Connection test completed ==="
